package component:cat-facts;

interface cat-facts {
    /// Get a random cat fact.
    get-random-fact: func() -> result<string, string>;
}

/// An example world for the component to target.
world cat-facts-dep {
    export cat-facts;
}
